@startuml
title Diagrama de Classes - Comercio de Produtos

skinparam classAttributeIconSize 0

class Cliente {
	}

class Catalogo {
	
}

class Produto {
	-id: int
	- nome: string
	- descricao: string
	- preco: decimal
	- ativo: bool
}

class EstoqueItem {
	+id: int
	+quantidadeDisponivel: int
	+reservar(qtd: int): bool
	+baixar(qtd: int)
	+repor(qtd: int)
}

class Carrinho {
	+id: int
	+subtotal: decimal
	+adicionarItem(produto: Produto, quantidade: int)
	+removerItem(produto: Produto)
	+calcularSubtotal(): decimal
	+limpar()
}

class ItemCarrinho {
	+quantidade: int
	+precoUnitario: decimal
	+calcularTotal(): decimal
}

class Pedido {
	+numero: string
	+dataCriacao: datetime
	+subtotal: decimal
	+frete: decimal
	+total: decimal
	+status: StatusPedido
	+confirmar()
	+cancelar()
}

class ItemPedido {
	+quantidade: int
	+precoUnitario: decimal
	+calcularTotal(): decimal
}

class EnderecoEntrega {
	+logradouro: string
	+numero: string
	+bairro: string
	+cidade: string
	+estado: string
	+cep: string
	+validar(): bool
}



class Entrega {
	+codigoRastreio: string
	+prazoDias: int
	+status: StatusEntrega
	+atualizarStatus(status: StatusEntrega)
}

Cliente  --  Carrinho
Cliente  --  Pedido
Catalogo  o--  Produto
Produto "1" -- "1" EstoqueItem

Carrinho "1" *-- "1..*" ItemCarrinho
ItemCarrinho "*" --> "1" Produto

Pedido "1" *-- "1..*" ItemPedido
ItemPedido "*" --> "1" Produto
Pedido "1" --> "1" EnderecoEntrega
Pedido "1" --> "1" Pagamento
Pedido "1" --> "0..1" Entrega

@enduml
